spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:authdb} # Added DB_PORT and DB_NAME for more flexibility
    username: ${DB_USER:authuser} # Changed default to authuser
    password: ${DB_PASS:authpassword} # Changed default to authpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # IMPORTANT: Use "validate" or "none" in production. Schema changes should be managed by Liquibase/Flyway.
    show-sql: false # Set to true for debugging, false for production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # If show-sql is true, this will format it nicely
  # Liquibase for database migrations (recommended for production)
  # liquibase:
  #   change-log: classpath:/db/changelog/db.changelog-master.yaml
  #   enabled: true

keycloak:
  realm: MySillyDreams-Realm
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080/auth} # PRD uses /auth, Keycloak official docs often use /realms
  resource: auth-service-client # This is the Client ID
  credentials:
    secret: ${KEYCLOAK_SECRET:dummysecret} # Placeholder, MUST be overridden by env var or K8s secret
  bearer-only: false # This service will have interactive login via /auth/login, so not bearer-only
  ssl-required: external # 'none' for local dev without SSL, 'external' or 'all' for prod
  # principal-attribute: preferred_username # or sub, email etc.
  # use-resource-role-mappings: true # If you map client roles to JWT instead of realm roles

kafka:
  bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false # To avoid adding __TypeId__ headers if not needed by consumer
  # consumer: # Example if this service also consumes events
    # group-id: auth-service-group
    # key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    # value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    # properties:
    #   spring.json.trusted.packages: "*" # Or specific packages

jwt:
  secret: ${JWT_SECRET:ChangeThisVerySecretKeyForProductionEnvironmentMinimum256Bits} # Placeholder, MUST be overridden
  expiration-ms: 3600000 # 1 hour
  # For asymmetric keys (RS256), you'd configure paths to key files or JWKS URI
  # public-key-location: "classpath:jwt/public.key"
  # private-key-location: "classpath:jwt/private.key"


server:
  port: 8080
  # For graceful shutdown
  shutdown: graceful
  # If behind a proxy, configure forwarded headers
  # forward-headers-strategy: framework # Or native, none

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus # Expose health, info, and prometheus (if micrometer-registry-prometheus is added)
  endpoint:
    health:
      show-details: when_authorized # Or "always" during dev, "never" for prod if sensitive
      # Probes can be enabled for Kubernetes
      probes:
        enabled: true
  # metrics: # Example for Prometheus if added
    # tags:
      # application: ${spring.application.name}

logging:
  level:
    root: INFO
    com.mysillydreams.auth: DEBUG # More specific logging for our app
    org.springframework.security: INFO # Can be DEBUG for troubleshooting security
    org.keycloak: INFO # Can be DEBUG for troubleshooting Keycloak integration
    # org.hibernate.SQL: DEBUG # To see SQL queries (if show-sql is false)
    # org.hibernate.type.descriptor.sql.BasicBinder: TRACE # To see bound parameters (if show-sql is false)

# Default Spring profiles
spring.profiles.active: ${SPRING_PROFILES_ACTIVE:default}

---
spring:
  config:
    activate:
      on-profile: kubernetes
  # Kubernetes specific configurations can go here
  # For example, if using Spring Cloud Kubernetes for ConfigMaps/Secrets
  # cloud:
    # kubernetes:
      # secrets:
        # enabled: true
        # sources:
          # - name: auth-service-secrets # Matches K8s Secret name
      # config:
        # enabled: true
        # sources:
          # - name: auth-service-config # Matches K8s ConfigMap name
# Add other profiles as needed (dev, test, prod)
# ---
# spring:
#   config:
#     activate:
#       on-profile: dev
#   jpa:
#     show-sql: true
#   keycloak:
#     ssl-required: none
# ---
# spring:
#   config:
#     activate:
#       on-profile: prod
#   jpa:
#     hibernate:
#       ddl-auto: validate # Safer in prod
#   keycloak:
#     ssl-required: all
#   management:
#     endpoint:
#       health:
#         show-details: never

# For Keycloak Admin Client (if not configured via code)
# keycloak.admin-client:
#   server-url: ${keycloak.auth-server-url}
#   realm: master # Or your app realm if service account has permissions there
#   client-id: admin-cli # Or a dedicated client for this service
#   client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET} # If using client secret
#   username: ${KEYCLOAK_ADMIN_USERNAME} # If using user credentials
#   password: ${KEYCLOAK_ADMIN_PASSWORD}
#   grant-type: client_credentials # Or password
