apiVersion: v1
kind: Secret
metadata:
  name: order-api-secret
  namespace: default # Or your target namespace
type: Opaque
data:
  # Values must be base64 encoded.
  # Example: echo -n "your-keycloak-client-secret" | base64
  KEYCLOAK_SECRET: "eW91ci1rZXljbG9hay1jbGllbnQtc2VjcmV0" # Replace with actual base64 encoded secret
  # Add other sensitive configurations here, e.g., database passwords if any
  # DB_PASSWORD: "your-db-password-base64-encoded"
---
# How to generate base64 values:
# For KEYCLOAK_SECRET:
#   echo -n "yourActualKeycloakSecretValue" | base64
#
# Ensure these secrets are properly managed, e.g., using Sealed Secrets, HashiCorp Vault, or other secrets management tools.
# This manifest is a basic K8s Secret. For production, consider more secure ways to inject secrets.
