server:
  port: 8080

spring:
  application:
    name: admin-server

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Spring Boot Admin configuration
spring.boot.admin:
  discovery:
    enabled: true
  ui:
    title: "MySillyDreams Platform Admin"
    brand: "MySillyDreams"

# Logging configuration
logging:
  level:
    de.codecentric.boot.admin: DEBUG
