spring:
  redis:
    host: redis.mysillydreams-dev
    port: 6379
    database: 2
    timeout: 2000ms
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service.mysillydreams-dev:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: http://user-service.mysillydreams-dev:8082
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server.mysillydreams-dev:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration-ms: 86400000

app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001,http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  security:
    enabled: false
  zipkin:
    tracing:
      endpoint: http://zipkin.mysillydreams-dev:9411/api/v2/spans

logging:
  level:
    root: INFO
    com.mysillydreams.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
