apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: dev # Assuming 'dev' namespace
data:
  # Kafka related
  KAFKA_BROKER: "kafka.dev.svc.cluster.local:9092"
  SCHEMA_REGISTRY_URL: "http://schema-registry.dev.svc.cluster.local:8081"

  # Database related (defaults are in application.yml, override if needed)
  DB_HOST: "postgres.dev.svc.cluster.local"
  DB_NAME: "paymentdb" # Matches default in payment's application.yml
  # DB_PORT: "5432"

  # RazorpayX Payout Account ID (Your account from which payouts are made)
  # RAZORPAY_KEY_ID will be moved to secrets for better security practice.
  RAZORPAY_X_ACCOUNT_ID: "your_razorpay_x_account_id" # From application.yml ${RAZORPAY_X_ACCOUNT_ID}

  # Application specific
  APP_COMMISSION_PERCENT: "10.0" # Default 10%, from application.yml ${APP_COMMISSION_PERCENT:10.0}

  # Outbox poller delays (if different from application.yml defaults needed for this env)
  # PAYMENT_OUTBOX_POLL_DELAY: "5000"
  # PAYMENT_OUTBOX_POLL_INITIALDELAY: "10000"

  # Keycloak related (if security is enabled for webhooks/APIs)
  # KEYCLOAK_URL: "https://keycloak.dev.svc.cluster.local/auth"
  # KEYCLOAK_REALM: "myrealm"
  # KEYCLOAK_CLIENT_ID: "payment-service-client"

  # Logging levels
  # LOGGING_LEVEL_COM_MYSILLYDREAMS_PAYMENT: "INFO"

  # Kafka Topics (application.yml has these defined, but listing them here can be for documentation or override if needed)
  # KAFKA_TOPIC_PAYMENT_REQUESTED: "order.payment.requested"
  # KAFKA_TOPIC_PAYMENT_SUCCEEDED: "order.payment.succeeded"
  # KAFKA_TOPIC_PAYMENT_FAILED: "order.payment.failed"
  # KAFKA_TOPIC_VENDOR_PAYOUT_INITIATED: "vendor.payout.initiated"
  # KAFKA_TOPIC_VENDOR_PAYOUT_SUCCEEDED: "vendor.payout.succeeded"
  # KAFKA_TOPIC_VENDOR_PAYOUT_FAILED: "vendor.payout.failed"
