apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secrets
  namespace: dev # Assuming 'dev' namespace
type: Opaque
stringData:
  # Database credentials (matching application.yml placeholders like ${DB_USER}, ${DB_PASS})
  DB_USER: "paymentuser_k8s" # Example, use actual secured credentials
  DB_PASS: "paymentpass_k8s_secret"

  # Razorpay API Credentials (matching application.yml placeholders)
  RAZORPAY_KEY_ID: "rzp_live_yourkeyid" # Or rzp_test_yourkeyid for non-prod
  RAZORPAY_KEY_SECRET: "your_razorpay_key_secret_value"

  # Razorpay Webhook Secret (matching application.yml placeholder)
  RAZORPAY_WEBHOOK_SECRET: "your_razorpay_webhook_secret_value"

  # Keycloak Client Secret (if Keycloak is enabled and client is confidential)
  # KEYCLOAK_CLIENT_SECRET: "your_payment_service_client_secret"

  # Any other sensitive configuration data
  # E.g., if Kafka requires SASL auth:
  # KAFKA_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"kafka_user\" password=\"kafka_secret_pass\";"
