apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: dev # Assuming 'dev' namespace
  labels:
    app: payment-service
spec:
  type: ClusterIP # For internal communication
  selector:
    app: payment-service # Matches labels in Deployment
  ports:
    - port: 8080 # Port other services in cluster use to call payment-service
                  # Could also be 8083 if direct port mapping is preferred internally
      targetPort: 8083 # Must match containerPort (8083) in Deployment
      protocol: TCP
      name: http
