server:
  port: 8083

spring:
  application:
    name: admin-server

  # Zookeeper Configuration
  cloud:
    zookeeper:
      connect-string: ${ZOOKEEPER_CONNECT_STRING:localhost:2181}
      config:
        enabled: true
        root: /mysillydreams
        default-context: ${ENVIRONMENT:dev}
        profile-separator: ','

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    db:
      enabled: false # Admin server doesn't have a database
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://zipkin:9411/api/v2/spans}

# Spring Boot Admin configuration
spring.boot.admin:
  discovery:
    enabled: true
  ui:
    title: "MySillyDreams Platform Admin"
    brand: "MySillyDreams"

# Logging configuration
logging:
  level:
    de.codecentric.boot.admin: DEBUG

---
spring:
  config:
    activate:
      on-profile: local
  application:
    name: admin-server

server:
  port: 8083

# Eureka Client Configuration for local
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Management endpoints for local tracing
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

# Spring Boot Admin configuration for local
spring.boot.admin:
  discovery:
    enabled: true
  ui:
    title: "MySillyDreams Platform Admin (Local)"
    brand: "MySillyDreams Local"

# Logging configuration for local
logging:
  level:
    de.codecentric.boot.admin: DEBUG
    com.mysillydreams: DEBUG
