spring:
  application:
    name: zookeeper-service

# Server Configuration
server:
  port: ${SERVER_PORT:8084}

# Zookeeper Configuration
zookeeper:
  connection-string: ${ZOOKEEPER_CONNECTION_STRING:localhost:2181}
  session-timeout: ${ZOOKEEPER_SESSION_TIMEOUT:60000}
  connection-timeout: ${ZOOKEEPER_CONNECTION_TIMEOUT:15000}

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  health:
    zookeeper:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://zipkin:9411/api/v2/spans}

# Security Configuration
spring.security:
  user:
    name: ${SECURITY_USER_NAME:admin}
    password: ${SECURITY_USER_PASSWORD:admin123}
    roles: ${SECURITY_USER_ROLES:ADMIN}

# Logging Configuration
logging:
  level:
    com.mysillydreams.zookeeper: DEBUG
    org.apache.zookeeper: INFO
    org.apache.curator: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"

---
# Local Development Profile
spring:
  config:
    activate:
      on-profile: local

# Local Zookeeper
zookeeper:
  connection-string: localhost:2181

# Local Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Local Zipkin
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

# Local Security
spring.security:
  user:
    name: admin
    password: admin123
    roles: ADMIN

logging:
  level:
    com.mysillydreams.zookeeper: DEBUG

---
# Development Environment Profile
spring:
  config:
    activate:
      on-profile: dev

zookeeper:
  connection-string: zookeeper-dev:2181

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-dev:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://zipkin-dev:9411/api/v2/spans

---
# QA Environment Profile
spring:
  config:
    activate:
      on-profile: qa

zookeeper:
  connection-string: zookeeper-qa:2181

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-qa:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://zipkin-qa:9411/api/v2/spans

---
# Staging Environment Profile
spring:
  config:
    activate:
      on-profile: staging

zookeeper:
  connection-string: zookeeper-staging:2181

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-staging:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://zipkin-staging:9411/api/v2/spans
