# Keycloak Deployment
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: mysillydreams-dev
data:
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://postgres-keycloak:5432/keycloak"
  KC_DB_USERNAME: "postgres"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HTTP_ENABLED: "true"
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
  JAVA_OPTS: "-Xms512m -Xmx1024m"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: mysillydreams-dev
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin123"
  KC_DB_PASSWORD: "postgres123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: mysillydreams-dev
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: keycloak/keycloak:23.0.7
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: keycloak-config
        - secretRef:
            name: keycloak-secrets
        command:
        - /opt/keycloak/bin/kc.sh
        - start-dev
        - --import-realm
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: mysillydreams-dev
  labels:
    app: keycloak
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: keycloak
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-nodeport
  namespace: mysillydreams-dev
  labels:
    app: keycloak
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30180
  selector:
    app: keycloak
