# API Gateway Deployment
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: mysillydreams-dev
data:
  # Bootstrap configuration only - all other config comes from Zookeeper
  SPRING_PROFILES_ACTIVE: "kubernetes"
  ENVIRONMENT: "dev"
  ZOOKEEPER_CONNECT_STRING: "zookeeper.mysillydreams-dev:2181"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: mysillydreams-dev
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: saaiiikrishna/api-gateway:dev-v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: api-gateway-config
        env:
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:+UseContainerSupport"
        - name: ZOOKEEPER_CONNECT_STRING
          valueFrom:
            configMapKeyRef:
              name: api-gateway-config
              key: ZOOKEEPER_CONNECT_STRING
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: mysillydreams-dev
  labels:
    app: api-gateway
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-nodeport
  namespace: mysillydreams-dev
  labels:
    app: api-gateway
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: http
  selector:
    app: api-gateway
