# API Gateway Deployment - Fixed for ZooKeeper Configuration Management
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: mysillydreams-dev
data:
  # Bootstrap configuration only - all other config comes from Zookeeper
  SPRING_PROFILES_ACTIVE: "dev"
  ENVIRONMENT: "dev"
  ZOOKEEPER_CONNECT_STRING: "zookeeper.mysillydreams-dev:2181"
  # CORS Configuration
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:3001,http://localhost:5173,http://localhost:8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: mysillydreams-dev
  labels:
    app: api-gateway
    component: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        component: gateway
    spec:
      # Add init container to wait for ZooKeeper
      initContainers:
      - name: wait-for-zookeeper
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for ZooKeeper to be ready..."
          until nc -z zookeeper.mysillydreams-dev 2181; do
            echo "ZooKeeper not ready, waiting..."
            sleep 5
          done
          echo "ZooKeeper is ready!"
      containers:
      - name: api-gateway
        image: api-gateway:1.4
        imagePullPolicy: Never
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:+UseContainerSupport"
        - name: ZOOKEEPER_CONNECT_STRING
          value: "zookeeper.mysillydreams-dev:2181"
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: ENVIRONMENT
          value: "dev"
        - name: SERVER_PORT
          value: "8080"
        - name: ROOT_LOG_LEVEL
          value: "INFO"
        # Redis configuration
        - name: SPRING_DATA_REDIS_HOST
          value: "redis.mysillydreams-dev"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        # Zipkin configuration
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          value: "http://zipkin.mysillydreams-dev:9411/api/v2/spans"
        - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
          value: "1.0"
        # CORS configuration
        - name: CORS_ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: api-gateway-config
              key: CORS_ALLOWED_ORIGINS
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: mysillydreams-dev
  labels:
    app: api-gateway
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-nodeport
  namespace: mysillydreams-dev
  labels:
    app: api-gateway
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: http
  selector:
    app: api-gateway
