# Admin Server Deployment
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-server-config
  namespace: mysillydreams-dev
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SPRING_APPLICATION_NAME: "admin-server"
  SERVER_PORT: "8083"
  ENVIRONMENT: "dev"
  ZOOKEEPER_CONNECT_STRING: "zookeeper.mysillydreams-dev:2181"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://eureka-server.mysillydreams-dev:8761/eureka/"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin.mysillydreams-dev:9411/api/v2/spans"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: mysillydreams-dev
  labels:
    app: admin-server
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
        component: monitoring
    spec:
      containers:
      - name: admin-server
        image: 172.22.208.1:5000/mysillydreams/admin-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
          name: http
        envFrom:
        - configMapRef:
            name: admin-server-config
        env:
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx512m -XX:+UseG1GC -XX:+UseContainerSupport"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: mysillydreams-dev
  labels:
    app: admin-server
spec:
  ports:
  - port: 8083
    targetPort: 8083
    name: http
  selector:
    app: admin-server
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server-nodeport
  namespace: mysillydreams-dev
  labels:
    app: admin-server
spec:
  type: NodePort
  ports:
  - port: 8083
    targetPort: 8083
    nodePort: 30083
    name: http
  selector:
    app: admin-server
