apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: mysillydreams
  labels:
    app: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - name: admin-server
        image: mysillydreams/admin-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_PROFILES_ACTIVE
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: EUREKA_SERVER_URL
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: mysillydreams
spec:
  selector:
    app: admin-server
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP

---
# NodePort service for external access to Admin UI
apiVersion: v1
kind: Service
metadata:
  name: admin-nodeport
  namespace: mysillydreams
spec:
  selector:
    app: admin-server
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort
