apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: mysillydreams
data:
  # Database Configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  AUTH_DB_NAME: "authdb"
  USER_DB_NAME: "userdb"
  DB_USER: "postgres"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Eureka Configuration
  EUREKA_SERVER_URL: "http://eureka-service:8761/eureka/"
  
  # Zipkin Configuration
  ZIPKIN_BASE_URL: "http://zipkin-service:9411"

  # Spring Boot Admin Configuration
  ADMIN_SERVER_URL: "http://admin-service:8080"

  # Keycloak Configuration
  KEYCLOAK_SERVER_URL: "http://keycloak-service:8080"
  KEYCLOAK_REALM: "mysillydreams"
  
  # Application Configuration
  SPRING_PROFILES_ACTIVE: "kubernetes"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: mysillydreams
type: Opaque
data:
  # Base64 encoded values
  DB_PASS: MDAwMA==  # "0000" in base64
  REDIS_PASSWORD: ""  # Empty password
