apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: mysillydreams
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: mysillydreams/eureka-server:latest
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_BOOT_ADMIN_CLIENT_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ADMIN_SERVER_URL
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 10
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: mysillydreams
spec:
  selector:
    app: eureka-server
  ports:
  - port: 8761
    targetPort: 8761
  type: ClusterIP

---
# NodePort service for external access to Eureka UI
apiVersion: v1
kind: Service
metadata:
  name: eureka-nodeport
  namespace: mysillydreams
spec:
  selector:
    app: eureka-server
  ports:
  - port: 8761
    targetPort: 8761
    nodePort: 30761
  type: NodePort
