apiVersion: v1
kind: Pod
metadata:
  name: temp-loader
  namespace: mysillydreams-dev
spec:
  restartPolicy: Never
  containers:
  - name: temp-loader
    image: docker:24-dind
    command: ["sleep", "600"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
