apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: mysillydreams
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: mysillydreams/user-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_PROFILES_ACTIVE
        - name: DB_URL
          value: "jdbc:postgresql://postgres-user-service:5432/userdb"
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASS
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_PORT
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: EUREKA_SERVER_URL
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          value: "http://zipkin-service:9411/api/v2/spans"
        - name: SPRING_BOOT_ADMIN_CLIENT_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ADMIN_SERVER_URL
        - name: VAULT_HOST
          value: "vault"
        - name: VAULT_PORT
          value: "8200"
        - name: VAULT_SCHEME
          value: "http"
        - name: VAULT_AUTH_METHOD
          value: "TOKEN"
        - name: VAULT_TOKEN
          value: "root-token"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 90
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 10
        imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: mysillydreams
spec:
  selector:
    app: user-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP

---
# NodePort service for external access
apiVersion: v1
kind: Service
metadata:
  name: user-nodeport
  namespace: mysillydreams
spec:
  selector:
    app: user-service
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30082
  type: NodePort
