apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: mysillydreams # Assuming a namespace, adjust if needed
data:
  # --- Spring Profile ---
  SPRING_PROFILES_ACTIVE: "kubernetes" # Activates kubernetes profile in application.yml

  # --- Keycloak URL ---
  # This should be the externally accessible URL for Keycloak if users are redirected,
  # or the internal K8s service URL if communication is purely backchannel.
  # The application.yml uses keycloak.auth-server-url
  KEYCLOAK_URL: "http://keycloak-http.keycloak.svc.cluster.local:8080/auth" # Example internal Keycloak service URL and path
  # For external access, it might be "https://keycloak.mysillydreams.com/auth"

  # --- Kafka Broker ---
  # This should be the address of your Kafka brokers, accessible from within the K8s cluster.
  KAFKA_BROKER: "kafka-service.kafka.svc.cluster.local:9092" # Example internal Kafka service URL

  # --- Application specific non-sensitive configurations ---
  # Example: LOG_LEVEL_COM_MYSILLYDREAMS_AUTH: "DEBUG"
  # These can override logging levels or other non-sensitive properties from application.yml
  # SERVER_PORT: "8080" # Already defaulted in Spring Boot, but can be overridden
  # MANAGEMENT_SERVER_PORT: "8081" # If actuator is on a different port
