apiVersion: v1
kind: Service
metadata:
  name: auth-service # This name can be used for service discovery within the cluster
  namespace: mysillydreams # Assuming a namespace
  labels:
    app: auth-service
    tier: backend
    component: authentication
spec:
  type: ClusterIP # Default type, exposes the service on an internal IP in the cluster.
                 # Use LoadBalancer for external cloud provider load balancer, or NodePort for specific needs.
  selector:
    app: auth-service # Selects pods with label "app: auth-service" (must match Deployment's template labels)
  ports:
  - name: http
    port: 80 # Port the service will be available on within the cluster
    targetPort: http # Name of the port on the Pods (must match a port name in Deployment's container spec)
                     # If targetPort is an integer, it directly refers to the containerPort.
                     # Using named ports is a good practice.
    protocol: TCP
  # - name: management # If actuator is on a different port and needs to be exposed via service
  #   port: 8081
  #   targetPort: management
  #   protocol: TCP
