---
# Zookeeper Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-service
  namespace: mysillydreams
  labels:
    app: zookeeper-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-service
  template:
    metadata:
      labels:
        app: zookeeper-service
    spec:
      containers:
      - name: zookeeper-service
        image: mysillydreams/zookeeper-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SERVER_PORT
          value: "8084"
        - name: ZOOKEEPER_CONNECTION_STRING
          value: "zookeeper-service:2181"
        - name: EUREKA_SERVER_URL
          value: "http://eureka-service:8761/eureka/"
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          value: "http://zipkin-service:9411/api/v2/spans"
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8084
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12

---
# Zookeeper Service ClusterIP Service
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service-svc
  namespace: mysillydreams
  labels:
    app: zookeeper-service
spec:
  type: ClusterIP
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
  selector:
    app: zookeeper-service

---
# Zookeeper Service NodePort Service for external access
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service-nodeport
  namespace: mysillydreams
  labels:
    app: zookeeper-service
spec:
  type: NodePort
  ports:
  - port: 8084
    targetPort: 8084
    nodePort: 30084
    protocol: TCP
  selector:
    app: zookeeper-service
