apiVersion: v1
kind: Secret
metadata:
  name: order-core-secret
  namespace: default # Or your target namespace
type: Opaque
data:
  # Values must be base64 encoded.
  # Example: echo -n "your-value" | base64

  # Database credentials
  DB_USER: "b3JkZXJfdXNlcg==" # Default: order_user
  DB_PASS: "b3JkZXJfcGFzcw==" # Default: order_pass

  # Keycloak client secret
  KEYCLOAK_SECRET: "eW91ci1vcmRlci1jb3JlLWNsaWVudC1zZWNyZXQ=" # Default: your-order-core-client-secret

  # Other sensitive configurations if any
  # e.g., API keys for external services
---
# How to generate base64 values:
# For DB_USER ('order_user'): echo -n "order_user" | base64 -> b3JkZXJfdXNlcg==
# For DB_PASS ('order_pass'): echo -n "order_pass" | base64 -> b3JkZXJfcGFzcw==
# For KEYCLOAK_SECRET ('your-order-core-client-secret'): echo -n "your-order-core-client-secret" | base64 -> eW91ci1vcmRlci1jb3JlLWNsaWVudC1zZWNyZXQ=
#
# Replace with your actual base64 encoded secrets.
# For production, manage these securely (e.g., Vault, Sealed Secrets).
