apiVersion: v1
kind: Secret
metadata:
  name: catalog-service-secret
  namespace: default # Or your target namespace
type: Opaque
data:
  # Base64 encoded secrets
  # Example: echo -n "mysecretpassword" | base64
  SPRING_DATASOURCE_USERNAME: "dXNlcg==" # Placeholder for base64 encoded "user"
  SPRING_DATASOURCE_PASSWORD: "cGFzc3dvcmQ=" # Placeholder for base64 encoded "password"

  # If OpenSearch or Redis requires authentication
  # OPENSEARCH_USERNAME: "YWRtaW4=" # Placeholder for base64 "admin"
  # OPENSEARCH_PASSWORD: "cGFzc3dvcmQ=" # Placeholder for base64 "password"
  # SPRING_REDIS_PASSWORD: "eW91cnJlZGlzcGFzc3dvcmQ=" # Placeholder

  # If using OAuth2 client credentials for some internal communication (not typical for resource server itself)
  # SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MYCLIENT_CLIENT_ID: "..."
  # SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MYCLIENT_CLIENT_SECRET: "..."

  # Any other sensitive configuration
  # MY_API_KEY: "c2VjcmV0YXBpa2V5"
---
# Example for using specific DB user/pass if not using SPRING_DATASOURCE_USERNAME/PASSWORD directly
# apiVersion: v1
# kind: Secret
# metadata:
#   name: catalog-db-credentials
# type: Opaque
# data:
#   DB_USER: "Y2F0YWxvZ191c2Vy" # catalog_user
#   DB_PASS: "c2VjdXJlcGFzc3dvcmQxMjMh" # securepassword123!
