apiVersion: v1
kind: Service
metadata:
  name: inventory-core
  namespace: dev # Assuming 'dev' namespace
  labels:
    app: inventory-core
spec:
  type: ClusterIP # Default type, suitable for internal services
  selector:
    app: inventory-core # Must match labels in Deployment's template.metadata.labels
  ports:
    - port: 8080 # Port other services in the cluster will use to reach inventory-core
      targetPort: 8082 # Must match containerPort in Deployment and server.port in application.yml
      protocol: TCP
      name: http # Name for the port (optional but good practice)
