apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-core-config
  namespace: dev # Assuming 'dev' namespace as per inventory-api example
data:
  KAFKA_BROKER: "kafka.dev.svc.cluster.local:9092"
  SCHEMA_REGISTRY_URL: "http://schema-registry.dev.svc.cluster.local:8081"
  DB_HOST: "postgres.dev.svc.cluster.local"
  # DB_NAME, DB_PORT are also used in application.yml, defaults are provided there
  # If they need to be overridden for K8s, add them here. E.g.:
  # DB_NAME: "inventorydb"
  # DB_PORT: "5432"

  # For outbox poller schedule, if made configurable beyond application.yml defaults
  # INVENTORY_OUTBOX_POLL_DELAY: "5000"
  # INVENTORY_OUTBOX_POLL_INITIALDELAY: "10000"

  # Keycloak related, if enabled and configured via env vars in application.yml
  # KEYCLOAK_URL: "https://keycloak.dev.svc.cluster.local/auth"
  # KEYCLOAK_REALM: "myrealm"
  # KEYCLOAK_CLIENT_ID: "inventory-core-client"

  # Logging levels, if needed to be configurable
  # LOGGING_LEVEL_COM_MYSILLYDREAMS_INVENTORYCORE: "INFO"
