apiVersion: v1
kind: Secret
metadata:
  name: inventory-core-secrets
  namespace: dev # Assuming 'dev' namespace
type: Opaque
stringData:
  # These keys must match the environment variables expected by application.yml
  # e.g., ${DB_USER}, ${DB_PASS}
  DB_USER: "inventory" # Default from guide
  DB_PASS: "inventory_pass" # Default from guide

  # If Keycloak client secret is used and configured via env var in application.yml:
  # KEYCLOAK_CLIENT_SECRET: "your-inventory-core-client-secret"

  # Any other sensitive configuration
  # For example, if Kafka needs SASL auth:
  # KAFKA_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"user\" password=\"pass\";"
